# Generated by Django 2.1 on 2019-11-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='abb',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
