# Generated by Django 2.1 on 2019-11-30 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('npb', '0002_team_abb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(default=999)),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=10)),
                ('position', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='npb.Team')),
            ],
        ),
    ]
