# Generated by Django 2.1 on 2019-11-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npb', '0003_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.IntegerField(default=0),
        ),
    ]
