# Generated by Django 2.1 on 2019-11-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npb', '0004_auto_20191130_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='no',
            field=models.CharField(default='999', max_length=5),
        ),
    ]
