# Generated by Django 2.1 on 2019-11-30 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('npb', '0005_auto_20191130_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=10)),
                ('result', models.IntegerField(default=0)),
                ('score', models.CharField(max_length=20)),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='npb.Team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='npb.Team')),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.AddField(
            model_name='matchresult',
            name='pitcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='npb.Player'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='team_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='npb.TeamYear'),
        ),
        migrations.AddField(
            model_name='player',
            name='team_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='npb.TeamYear'),
        ),
    ]
