# Generated by Django 2.1 on 2019-12-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npb', '0007_auto_20191130_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hitterstats',
            name='no1',
        ),
        migrations.AddField(
            model_name='hitterstats',
            name='noi',
            field=models.FloatField(default=0.0),
        ),
    ]
