# Generated by Django 2.1 on 2019-12-01 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('npb', '0009_auto_20191201_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pitcherstats',
            old_name='hidaritsu',
            new_name='hiannda',
        ),
    ]
