# Generated by Django 2.1 on 2019-12-01 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('npb', '0010_auto_20191201_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pitcherstats',
            old_name='save',
            new_name='saves',
        ),
    ]
