# Generated by Django 2.1 on 2019-12-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npb', '0011_auto_20191201_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='spell',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
