# Generated by Django 2.1 on 2019-12-01 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('npb', '0012_team_spell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='pitcher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='npb.Player'),
        ),
    ]
