# Generated by Django 2.1 on 2019-12-01 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('npb', '0014_matchmember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchmember',
            old_name='eights',
            new_name='eighth',
        ),
    ]
