# Generated by Django 2.1 on 2019-12-01 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('npb', '0015_auto_20191201_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchresult',
            old_name='data',
            new_name='date',
        ),
    ]
