# Generated by Django 2.1 on 2019-12-01 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('npb', '0017_matchresult_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchmember',
            name='eighth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='eights', to='npb.Player'),
        ),
        migrations.AlterField(
            model_name='matchmember',
            name='fifth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fifth', to='npb.Player'),
        ),
        migrations.AlterField(
            model_name='matchmember',
            name='first',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='first', to='npb.Player'),
        ),
        migrations.AlterField(
            model_name='matchmember',
            name='fourth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fourth', to='npb.Player'),
        ),
        migrations.AlterField(
            model_name='matchmember',
            name='nineth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nineth', to='npb.Player'),
        ),
        migrations.AlterField(
            model_name='matchmember',
            name='second',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='second', to='npb.Player'),
        ),
        migrations.AlterField(
            model_name='matchmember',
            name='seventh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='seventh', to='npb.Player'),
        ),
        migrations.AlterField(
            model_name='matchmember',
            name='sixth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sixth', to='npb.Player'),
        ),
        migrations.AlterField(
            model_name='matchmember',
            name='third',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='third', to='npb.Player'),
        ),
    ]
