# Generated by Django 2.1 on 2019-12-03 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('npb', '0018_auto_20191201_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('fifth', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fifth', to='npb.Team')),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='first', to='npb.Team')),
                ('fourth', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fourth', to='npb.Team')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='second', to='npb.Team')),
                ('sixth', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sixth', to='npb.Team')),
                ('third', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='third', to='npb.Team')),
            ],
        ),
    ]
