# Generated by Django 2.1 on 2019-12-03 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('npb', '0019_ranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='ranking',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='npb.League'),
        ),
        migrations.AddField(
            model_name='team',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='npb.League'),
        ),
    ]
